services:
  rogeriogoulart:
    container_name: rogeriogoulart
    image: rogeriogoulart
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5174:5174"
    volumes:
      - ./:/app
      - node_modules:/app/node_modules
      - pnpm_store:/pnpm/store
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true # Necessário para hot-reload no Docker
      - PNPM_STORE_DIR=/pnpm/store
      - CI=true
    command: sh -c "pnpm install --frozen-lockfile && pnpm run dev --host --port 5174"

volumes:
  node_modules:
  pnpm_store:
